### ISSUE TITLE
How to prepare the .pkl file for training?

### ISSUE THREAD

**Issue by HLH13297997663** [lyakaap/Landmark2019-1st-and-3rd-Place-Solution#4]

**Comment by lyakaap** [comment]
I cleaned up the setup code and wrote the code for preparing pkl file from csv file.
https://github.com/lyakaap/Landmark2019-1st-and-3rd-Place-Solution/blob/master/src/prepare_dataset.py

**Comment by HLH13297997663** [comment]
Thank you very much

**Comment by kxhit** [comment]
Hi guys! @HLH13297997663  @lyakaap 
When I run `python3 v2clean.py tuning -d 0,1,2,3 --n-gpu 2`, I got error `No such file or directory: input/gld_v2train.pkl` ```
in make_train_loaders
    train = pd.read_pickle(data_root + 'train.pkl')
```
Could you help me? How to solve it? Thanks a lot!

**Comment by Cabbagehust2507** [comment]
> Hi guys! @HLH13297997663 @lyakaap
> When I run `python3 v2clean.py tuning -d 0,1,2,3 --n-gpu 2`, I got error `No such file or directory: input/gld_v2train.pkl` ```
> in make_train_loaders
> train = pd.read_pickle(data_root + 'train.pkl')
> 
> ```
> Could you help me? How to solve it? Thanks a lot!
> ```

Try creat pkl file by https://github.com/lyakaap/Landmark2019-1st-and-3rd-Place-Solution/blob/master/src/prepare_dataset.py and put it into input.
