### ISSUE TITLE
Resnet-101 results by training on GLD-v2 only

### ISSUE THREAD

**Issue by andrefaraujo** [lyakaap/Landmark2019-1st-and-3rd-Place-Solution#5]
Hi @lyakaap ,

The README mentions ResNet-101-ArcFace results by training on GLD-v1, or GLD-v1 combined with GLD-v2. Would you have results of training on GLD-v2 only? (clean version mainly)

Thanks!

**Comment by lyakaap** [comment]
Thank you for your interests in our experimental results!
Unfortunately, I haven't experimented yet in those settings. But I think it's worth a shot, and I will report the results on README if I will have been done those experiments.

**Comment by lyakaap** [comment]
@andrefaraujo Updated README. Now you can see the results of GLD-v2 only (both nosiy and clean).

**Comment by andrefaraujo** [comment]
Excellent, thanks so much @lyakaap !
